/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PatientsService } from "../patients.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PatientsCreateInput } from "./PatientsCreateInput";
import { Patients } from "./Patients";
import { PatientsFindManyArgs } from "./PatientsFindManyArgs";
import { PatientsWhereUniqueInput } from "./PatientsWhereUniqueInput";
import { PatientsUpdateInput } from "./PatientsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PatientsControllerBase {
  constructor(
    protected readonly service: PatientsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Patients })
  @nestAccessControl.UseRoles({
    resource: "Patients",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPatients(
    @common.Body() data: PatientsCreateInput
  ): Promise<Patients> {
    return await this.service.createPatients({
      data: data,
      select: {
        createdAt: true,
        id: true,
        ptDateOfBirth: true,
        ptGender: true,
        ptRolesId: true,
        ptUmsId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Patients] })
  @ApiNestedQuery(PatientsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Patients",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async patientsItems(@common.Req() request: Request): Promise<Patients[]> {
    const args = plainToClass(PatientsFindManyArgs, request.query);
    return this.service.patientsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        ptDateOfBirth: true,
        ptGender: true,
        ptRolesId: true,
        ptUmsId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Patients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Patients",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async patients(
    @common.Param() params: PatientsWhereUniqueInput
  ): Promise<Patients | null> {
    const result = await this.service.patients({
      where: params,
      select: {
        createdAt: true,
        id: true,
        ptDateOfBirth: true,
        ptGender: true,
        ptRolesId: true,
        ptUmsId: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Patients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Patients",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePatients(
    @common.Param() params: PatientsWhereUniqueInput,
    @common.Body() data: PatientsUpdateInput
  ): Promise<Patients | null> {
    try {
      return await this.service.updatePatients({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          ptDateOfBirth: true,
          ptGender: true,
          ptRolesId: true,
          ptUmsId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Patients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Patients",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePatients(
    @common.Param() params: PatientsWhereUniqueInput
  ): Promise<Patients | null> {
    try {
      return await this.service.deletePatients({
        where: params,
        select: {
          createdAt: true,
          id: true,
          ptDateOfBirth: true,
          ptGender: true,
          ptRolesId: true,
          ptUmsId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
