/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LabResultsService } from "../labResults.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LabResultsCreateInput } from "./LabResultsCreateInput";
import { LabResults } from "./LabResults";
import { LabResultsFindManyArgs } from "./LabResultsFindManyArgs";
import { LabResultsWhereUniqueInput } from "./LabResultsWhereUniqueInput";
import { LabResultsUpdateInput } from "./LabResultsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LabResultsControllerBase {
  constructor(
    protected readonly service: LabResultsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LabResults })
  @nestAccessControl.UseRoles({
    resource: "LabResults",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLabResults(
    @common.Body() data: LabResultsCreateInput
  ): Promise<LabResults> {
    return await this.service.createLabResults({
      data: data,
      select: {
        createdAt: true,
        id: true,
        lbrLabTechnicianId: true,
        lbrPatientId: true,
        lbrResultDate: true,
        lbrResultDetails: true,
        lbrRolesId: true,
        lbrStatus: true,
        lbrTestType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [LabResults] })
  @ApiNestedQuery(LabResultsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LabResults",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async labResultsItems(@common.Req() request: Request): Promise<LabResults[]> {
    const args = plainToClass(LabResultsFindManyArgs, request.query);
    return this.service.labResultsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        lbrLabTechnicianId: true,
        lbrPatientId: true,
        lbrResultDate: true,
        lbrResultDetails: true,
        lbrRolesId: true,
        lbrStatus: true,
        lbrTestType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LabResults })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LabResults",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async labResults(
    @common.Param() params: LabResultsWhereUniqueInput
  ): Promise<LabResults | null> {
    const result = await this.service.labResults({
      where: params,
      select: {
        createdAt: true,
        id: true,
        lbrLabTechnicianId: true,
        lbrPatientId: true,
        lbrResultDate: true,
        lbrResultDetails: true,
        lbrRolesId: true,
        lbrStatus: true,
        lbrTestType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LabResults })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LabResults",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLabResults(
    @common.Param() params: LabResultsWhereUniqueInput,
    @common.Body() data: LabResultsUpdateInput
  ): Promise<LabResults | null> {
    try {
      return await this.service.updateLabResults({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          lbrLabTechnicianId: true,
          lbrPatientId: true,
          lbrResultDate: true,
          lbrResultDetails: true,
          lbrRolesId: true,
          lbrStatus: true,
          lbrTestType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LabResults })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LabResults",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLabResults(
    @common.Param() params: LabResultsWhereUniqueInput
  ): Promise<LabResults | null> {
    try {
      return await this.service.deleteLabResults({
        where: params,
        select: {
          createdAt: true,
          id: true,
          lbrLabTechnicianId: true,
          lbrPatientId: true,
          lbrResultDate: true,
          lbrResultDetails: true,
          lbrRolesId: true,
          lbrStatus: true,
          lbrTestType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
