/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HospitalDetailsService } from "../hospitalDetails.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HospitalDetailsCreateInput } from "./HospitalDetailsCreateInput";
import { HospitalDetails } from "./HospitalDetails";
import { HospitalDetailsFindManyArgs } from "./HospitalDetailsFindManyArgs";
import { HospitalDetailsWhereUniqueInput } from "./HospitalDetailsWhereUniqueInput";
import { HospitalDetailsUpdateInput } from "./HospitalDetailsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HospitalDetailsControllerBase {
  constructor(
    protected readonly service: HospitalDetailsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HospitalDetails })
  @nestAccessControl.UseRoles({
    resource: "HospitalDetails",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHospitalDetails(
    @common.Body() data: HospitalDetailsCreateInput
  ): Promise<HospitalDetails> {
    return await this.service.createHospitalDetails({
      data: data,
      select: {
        createdAt: true,
        hdAffiliationNumber: true,
        hdHospitalId: true,
        hdHospitalType: true,
        hdSpeciality: true,
        hdStatus: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HospitalDetails] })
  @ApiNestedQuery(HospitalDetailsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HospitalDetails",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hospitalDetailsItems(
    @common.Req() request: Request
  ): Promise<HospitalDetails[]> {
    const args = plainToClass(HospitalDetailsFindManyArgs, request.query);
    return this.service.hospitalDetailsItems({
      ...args,
      select: {
        createdAt: true,
        hdAffiliationNumber: true,
        hdHospitalId: true,
        hdHospitalType: true,
        hdSpeciality: true,
        hdStatus: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HospitalDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HospitalDetails",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hospitalDetails(
    @common.Param() params: HospitalDetailsWhereUniqueInput
  ): Promise<HospitalDetails | null> {
    const result = await this.service.hospitalDetails({
      where: params,
      select: {
        createdAt: true,
        hdAffiliationNumber: true,
        hdHospitalId: true,
        hdHospitalType: true,
        hdSpeciality: true,
        hdStatus: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HospitalDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HospitalDetails",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHospitalDetails(
    @common.Param() params: HospitalDetailsWhereUniqueInput,
    @common.Body() data: HospitalDetailsUpdateInput
  ): Promise<HospitalDetails | null> {
    try {
      return await this.service.updateHospitalDetails({
        where: params,
        data: data,
        select: {
          createdAt: true,
          hdAffiliationNumber: true,
          hdHospitalId: true,
          hdHospitalType: true,
          hdSpeciality: true,
          hdStatus: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HospitalDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HospitalDetails",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHospitalDetails(
    @common.Param() params: HospitalDetailsWhereUniqueInput
  ): Promise<HospitalDetails | null> {
    try {
      return await this.service.deleteHospitalDetails({
        where: params,
        select: {
          createdAt: true,
          hdAffiliationNumber: true,
          hdHospitalId: true,
          hdHospitalType: true,
          hdSpeciality: true,
          hdStatus: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
