/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DiseaseOutbreaksService } from "../diseaseOutbreaks.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DiseaseOutbreaksCreateInput } from "./DiseaseOutbreaksCreateInput";
import { DiseaseOutbreaks } from "./DiseaseOutbreaks";
import { DiseaseOutbreaksFindManyArgs } from "./DiseaseOutbreaksFindManyArgs";
import { DiseaseOutbreaksWhereUniqueInput } from "./DiseaseOutbreaksWhereUniqueInput";
import { DiseaseOutbreaksUpdateInput } from "./DiseaseOutbreaksUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DiseaseOutbreaksControllerBase {
  constructor(
    protected readonly service: DiseaseOutbreaksService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DiseaseOutbreaks })
  @nestAccessControl.UseRoles({
    resource: "DiseaseOutbreaks",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDiseaseOutbreaks(
    @common.Body() data: DiseaseOutbreaksCreateInput
  ): Promise<DiseaseOutbreaks> {
    return await this.service.createDiseaseOutbreaks({
      data: data,
      select: {
        createdAt: true,
        dobCaseCount: true,
        dobDiseaseName: true,
        dobLatestUpdate: true,
        dobLocation: true,
        dobRolesId: true,
        dobStartDate: true,
        dobStatus: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DiseaseOutbreaks] })
  @ApiNestedQuery(DiseaseOutbreaksFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DiseaseOutbreaks",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async diseaseOutbreaksItems(
    @common.Req() request: Request
  ): Promise<DiseaseOutbreaks[]> {
    const args = plainToClass(DiseaseOutbreaksFindManyArgs, request.query);
    return this.service.diseaseOutbreaksItems({
      ...args,
      select: {
        createdAt: true,
        dobCaseCount: true,
        dobDiseaseName: true,
        dobLatestUpdate: true,
        dobLocation: true,
        dobRolesId: true,
        dobStartDate: true,
        dobStatus: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DiseaseOutbreaks })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiseaseOutbreaks",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async diseaseOutbreaks(
    @common.Param() params: DiseaseOutbreaksWhereUniqueInput
  ): Promise<DiseaseOutbreaks | null> {
    const result = await this.service.diseaseOutbreaks({
      where: params,
      select: {
        createdAt: true,
        dobCaseCount: true,
        dobDiseaseName: true,
        dobLatestUpdate: true,
        dobLocation: true,
        dobRolesId: true,
        dobStartDate: true,
        dobStatus: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DiseaseOutbreaks })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiseaseOutbreaks",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDiseaseOutbreaks(
    @common.Param() params: DiseaseOutbreaksWhereUniqueInput,
    @common.Body() data: DiseaseOutbreaksUpdateInput
  ): Promise<DiseaseOutbreaks | null> {
    try {
      return await this.service.updateDiseaseOutbreaks({
        where: params,
        data: data,
        select: {
          createdAt: true,
          dobCaseCount: true,
          dobDiseaseName: true,
          dobLatestUpdate: true,
          dobLocation: true,
          dobRolesId: true,
          dobStartDate: true,
          dobStatus: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DiseaseOutbreaks })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiseaseOutbreaks",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDiseaseOutbreaks(
    @common.Param() params: DiseaseOutbreaksWhereUniqueInput
  ): Promise<DiseaseOutbreaks | null> {
    try {
      return await this.service.deleteDiseaseOutbreaks({
        where: params,
        select: {
          createdAt: true,
          dobCaseCount: true,
          dobDiseaseName: true,
          dobLatestUpdate: true,
          dobLocation: true,
          dobRolesId: true,
          dobStartDate: true,
          dobStatus: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
