/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DoctorDetailsService } from "../doctorDetails.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DoctorDetailsCreateInput } from "./DoctorDetailsCreateInput";
import { DoctorDetails } from "./DoctorDetails";
import { DoctorDetailsFindManyArgs } from "./DoctorDetailsFindManyArgs";
import { DoctorDetailsWhereUniqueInput } from "./DoctorDetailsWhereUniqueInput";
import { DoctorDetailsUpdateInput } from "./DoctorDetailsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DoctorDetailsControllerBase {
  constructor(
    protected readonly service: DoctorDetailsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DoctorDetails })
  @nestAccessControl.UseRoles({
    resource: "DoctorDetails",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDoctorDetails(
    @common.Body() data: DoctorDetailsCreateInput
  ): Promise<DoctorDetails> {
    return await this.service.createDoctorDetails({
      data: data,
      select: {
        createdAt: true,
        ddAvailability: true,
        ddDoctorId: true,
        ddMedicalId: true,
        ddPhoto: true,
        ddQualification: true,
        ddStatus: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DoctorDetails] })
  @ApiNestedQuery(DoctorDetailsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DoctorDetails",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async doctorDetailsItems(
    @common.Req() request: Request
  ): Promise<DoctorDetails[]> {
    const args = plainToClass(DoctorDetailsFindManyArgs, request.query);
    return this.service.doctorDetailsItems({
      ...args,
      select: {
        createdAt: true,
        ddAvailability: true,
        ddDoctorId: true,
        ddMedicalId: true,
        ddPhoto: true,
        ddQualification: true,
        ddStatus: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DoctorDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DoctorDetails",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async doctorDetails(
    @common.Param() params: DoctorDetailsWhereUniqueInput
  ): Promise<DoctorDetails | null> {
    const result = await this.service.doctorDetails({
      where: params,
      select: {
        createdAt: true,
        ddAvailability: true,
        ddDoctorId: true,
        ddMedicalId: true,
        ddPhoto: true,
        ddQualification: true,
        ddStatus: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DoctorDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DoctorDetails",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDoctorDetails(
    @common.Param() params: DoctorDetailsWhereUniqueInput,
    @common.Body() data: DoctorDetailsUpdateInput
  ): Promise<DoctorDetails | null> {
    try {
      return await this.service.updateDoctorDetails({
        where: params,
        data: data,
        select: {
          createdAt: true,
          ddAvailability: true,
          ddDoctorId: true,
          ddMedicalId: true,
          ddPhoto: true,
          ddQualification: true,
          ddStatus: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DoctorDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DoctorDetails",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDoctorDetails(
    @common.Param() params: DoctorDetailsWhereUniqueInput
  ): Promise<DoctorDetails | null> {
    try {
      return await this.service.deleteDoctorDetails({
        where: params,
        select: {
          createdAt: true,
          ddAvailability: true,
          ddDoctorId: true,
          ddMedicalId: true,
          ddPhoto: true,
          ddQualification: true,
          ddStatus: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
