/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DoctorsService } from "../doctors.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DoctorsCreateInput } from "./DoctorsCreateInput";
import { Doctors } from "./Doctors";
import { DoctorsFindManyArgs } from "./DoctorsFindManyArgs";
import { DoctorsWhereUniqueInput } from "./DoctorsWhereUniqueInput";
import { DoctorsUpdateInput } from "./DoctorsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DoctorsControllerBase {
  constructor(
    protected readonly service: DoctorsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Doctors })
  @nestAccessControl.UseRoles({
    resource: "Doctors",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDoctors(
    @common.Body() data: DoctorsCreateInput
  ): Promise<Doctors> {
    return await this.service.createDoctors({
      data: data,
      select: {
        createdAt: true,
        drRolesId: true,
        drSpecialization: true,
        drUmsId: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Doctors] })
  @ApiNestedQuery(DoctorsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Doctors",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async doctorsItems(@common.Req() request: Request): Promise<Doctors[]> {
    const args = plainToClass(DoctorsFindManyArgs, request.query);
    return this.service.doctorsItems({
      ...args,
      select: {
        createdAt: true,
        drRolesId: true,
        drSpecialization: true,
        drUmsId: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Doctors })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Doctors",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async doctors(
    @common.Param() params: DoctorsWhereUniqueInput
  ): Promise<Doctors | null> {
    const result = await this.service.doctors({
      where: params,
      select: {
        createdAt: true,
        drRolesId: true,
        drSpecialization: true,
        drUmsId: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Doctors })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Doctors",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDoctors(
    @common.Param() params: DoctorsWhereUniqueInput,
    @common.Body() data: DoctorsUpdateInput
  ): Promise<Doctors | null> {
    try {
      return await this.service.updateDoctors({
        where: params,
        data: data,
        select: {
          createdAt: true,
          drRolesId: true,
          drSpecialization: true,
          drUmsId: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Doctors })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Doctors",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDoctors(
    @common.Param() params: DoctorsWhereUniqueInput
  ): Promise<Doctors | null> {
    try {
      return await this.service.deleteDoctors({
        where: params,
        select: {
          createdAt: true,
          drRolesId: true,
          drSpecialization: true,
          drUmsId: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
