/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MedicalRecordsService } from "../medicalRecords.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MedicalRecordsCreateInput } from "./MedicalRecordsCreateInput";
import { MedicalRecords } from "./MedicalRecords";
import { MedicalRecordsFindManyArgs } from "./MedicalRecordsFindManyArgs";
import { MedicalRecordsWhereUniqueInput } from "./MedicalRecordsWhereUniqueInput";
import { MedicalRecordsUpdateInput } from "./MedicalRecordsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MedicalRecordsControllerBase {
  constructor(
    protected readonly service: MedicalRecordsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MedicalRecords })
  @nestAccessControl.UseRoles({
    resource: "MedicalRecords",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMedicalRecords(
    @common.Body() data: MedicalRecordsCreateInput
  ): Promise<MedicalRecords> {
    return await this.service.createMedicalRecords({
      data: data,
      select: {
        createdAt: true,
        id: true,
        mrDateOfRecord: true,
        mrDoctorId: true,
        mrDocumentContent: true,
        mrDocumentType: true,
        mrHospitalDb: true,
        mrPatientId: true,
        mrRolesId: true,
        mrStatus: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MedicalRecords] })
  @ApiNestedQuery(MedicalRecordsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MedicalRecords",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async medicalRecordsItems(
    @common.Req() request: Request
  ): Promise<MedicalRecords[]> {
    const args = plainToClass(MedicalRecordsFindManyArgs, request.query);
    return this.service.medicalRecordsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        mrDateOfRecord: true,
        mrDoctorId: true,
        mrDocumentContent: true,
        mrDocumentType: true,
        mrHospitalDb: true,
        mrPatientId: true,
        mrRolesId: true,
        mrStatus: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MedicalRecords })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MedicalRecords",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async medicalRecords(
    @common.Param() params: MedicalRecordsWhereUniqueInput
  ): Promise<MedicalRecords | null> {
    const result = await this.service.medicalRecords({
      where: params,
      select: {
        createdAt: true,
        id: true,
        mrDateOfRecord: true,
        mrDoctorId: true,
        mrDocumentContent: true,
        mrDocumentType: true,
        mrHospitalDb: true,
        mrPatientId: true,
        mrRolesId: true,
        mrStatus: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MedicalRecords })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MedicalRecords",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMedicalRecords(
    @common.Param() params: MedicalRecordsWhereUniqueInput,
    @common.Body() data: MedicalRecordsUpdateInput
  ): Promise<MedicalRecords | null> {
    try {
      return await this.service.updateMedicalRecords({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          mrDateOfRecord: true,
          mrDoctorId: true,
          mrDocumentContent: true,
          mrDocumentType: true,
          mrHospitalDb: true,
          mrPatientId: true,
          mrRolesId: true,
          mrStatus: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MedicalRecords })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MedicalRecords",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMedicalRecords(
    @common.Param() params: MedicalRecordsWhereUniqueInput
  ): Promise<MedicalRecords | null> {
    try {
      return await this.service.deleteMedicalRecords({
        where: params,
        select: {
          createdAt: true,
          id: true,
          mrDateOfRecord: true,
          mrDoctorId: true,
          mrDocumentContent: true,
          mrDocumentType: true,
          mrHospitalDb: true,
          mrPatientId: true,
          mrRolesId: true,
          mrStatus: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
