/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Login } from "./Login";
import { LoginCountArgs } from "./LoginCountArgs";
import { LoginFindManyArgs } from "./LoginFindManyArgs";
import { LoginFindUniqueArgs } from "./LoginFindUniqueArgs";
import { CreateLoginArgs } from "./CreateLoginArgs";
import { UpdateLoginArgs } from "./UpdateLoginArgs";
import { DeleteLoginArgs } from "./DeleteLoginArgs";
import { LoginService } from "../login.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Login)
export class LoginResolverBase {
  constructor(
    protected readonly service: LoginService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "read",
    possession: "any",
  })
  async _loginsMeta(
    @graphql.Args() args: LoginCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Login])
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "read",
    possession: "any",
  })
  async logins(@graphql.Args() args: LoginFindManyArgs): Promise<Login[]> {
    return this.service.logins(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Login, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "read",
    possession: "own",
  })
  async login(
    @graphql.Args() args: LoginFindUniqueArgs
  ): Promise<Login | null> {
    const result = await this.service.login(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Login)
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "create",
    possession: "any",
  })
  async createLogin(@graphql.Args() args: CreateLoginArgs): Promise<Login> {
    return await this.service.createLogin({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Login)
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "update",
    possession: "any",
  })
  async updateLogin(
    @graphql.Args() args: UpdateLoginArgs
  ): Promise<Login | null> {
    try {
      return await this.service.updateLogin({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Login)
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "delete",
    possession: "any",
  })
  async deleteLogin(
    @graphql.Args() args: DeleteLoginArgs
  ): Promise<Login | null> {
    try {
      return await this.service.deleteLogin(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
