/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Login as PrismaLogin } from "@prisma/client";

export class LoginServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.LoginCountArgs, "select">): Promise<number> {
    return this.prisma.login.count(args);
  }

  async logins(args: Prisma.LoginFindManyArgs): Promise<PrismaLogin[]> {
    return this.prisma.login.findMany(args);
  }
  async login(args: Prisma.LoginFindUniqueArgs): Promise<PrismaLogin | null> {
    return this.prisma.login.findUnique(args);
  }
  async createLogin(args: Prisma.LoginCreateArgs): Promise<PrismaLogin> {
    return this.prisma.login.create(args);
  }
  async updateLogin(args: Prisma.LoginUpdateArgs): Promise<PrismaLogin> {
    return this.prisma.login.update(args);
  }
  async deleteLogin(args: Prisma.LoginDeleteArgs): Promise<PrismaLogin> {
    return this.prisma.login.delete(args);
  }
}
