/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RolesService } from "../roles.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RolesCreateInput } from "./RolesCreateInput";
import { Roles } from "./Roles";
import { RolesFindManyArgs } from "./RolesFindManyArgs";
import { RolesWhereUniqueInput } from "./RolesWhereUniqueInput";
import { RolesUpdateInput } from "./RolesUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RolesControllerBase {
  constructor(
    protected readonly service: RolesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Roles })
  @nestAccessControl.UseRoles({
    resource: "Roles",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRoles(@common.Body() data: RolesCreateInput): Promise<Roles> {
    return await this.service.createRoles({
      data: data,
      select: {
        createdAt: true,
        id: true,
        rleRoleName: true,
        roleName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Roles] })
  @ApiNestedQuery(RolesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Roles",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rolesItems(@common.Req() request: Request): Promise<Roles[]> {
    const args = plainToClass(RolesFindManyArgs, request.query);
    return this.service.rolesItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        rleRoleName: true,
        roleName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Roles })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Roles",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async roles(
    @common.Param() params: RolesWhereUniqueInput
  ): Promise<Roles | null> {
    const result = await this.service.roles({
      where: params,
      select: {
        createdAt: true,
        id: true,
        rleRoleName: true,
        roleName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Roles })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Roles",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRoles(
    @common.Param() params: RolesWhereUniqueInput,
    @common.Body() data: RolesUpdateInput
  ): Promise<Roles | null> {
    try {
      return await this.service.updateRoles({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          rleRoleName: true,
          roleName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Roles })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Roles",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRoles(
    @common.Param() params: RolesWhereUniqueInput
  ): Promise<Roles | null> {
    try {
      return await this.service.deleteRoles({
        where: params,
        select: {
          createdAt: true,
          id: true,
          rleRoleName: true,
          roleName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
