/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ComplaintsService } from "../complaints.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ComplaintsCreateInput } from "./ComplaintsCreateInput";
import { Complaints } from "./Complaints";
import { ComplaintsFindManyArgs } from "./ComplaintsFindManyArgs";
import { ComplaintsWhereUniqueInput } from "./ComplaintsWhereUniqueInput";
import { ComplaintsUpdateInput } from "./ComplaintsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ComplaintsControllerBase {
  constructor(
    protected readonly service: ComplaintsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Complaints })
  @nestAccessControl.UseRoles({
    resource: "Complaints",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createComplaints(
    @common.Body() data: ComplaintsCreateInput
  ): Promise<Complaints> {
    return await this.service.createComplaints({
      data: data,
      select: {
        cpDescription: true,
        cpResolution: true,
        cpRolesId: true,
        cpStatus: true,
        cpSubject: true,
        cpUmsId: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Complaints] })
  @ApiNestedQuery(ComplaintsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Complaints",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async complaintsItems(@common.Req() request: Request): Promise<Complaints[]> {
    const args = plainToClass(ComplaintsFindManyArgs, request.query);
    return this.service.complaintsItems({
      ...args,
      select: {
        cpDescription: true,
        cpResolution: true,
        cpRolesId: true,
        cpStatus: true,
        cpSubject: true,
        cpUmsId: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Complaints })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Complaints",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async complaints(
    @common.Param() params: ComplaintsWhereUniqueInput
  ): Promise<Complaints | null> {
    const result = await this.service.complaints({
      where: params,
      select: {
        cpDescription: true,
        cpResolution: true,
        cpRolesId: true,
        cpStatus: true,
        cpSubject: true,
        cpUmsId: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Complaints })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Complaints",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateComplaints(
    @common.Param() params: ComplaintsWhereUniqueInput,
    @common.Body() data: ComplaintsUpdateInput
  ): Promise<Complaints | null> {
    try {
      return await this.service.updateComplaints({
        where: params,
        data: data,
        select: {
          cpDescription: true,
          cpResolution: true,
          cpRolesId: true,
          cpStatus: true,
          cpSubject: true,
          cpUmsId: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Complaints })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Complaints",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteComplaints(
    @common.Param() params: ComplaintsWhereUniqueInput
  ): Promise<Complaints | null> {
    try {
      return await this.service.deleteComplaints({
        where: params,
        select: {
          cpDescription: true,
          cpResolution: true,
          cpRolesId: true,
          cpStatus: true,
          cpSubject: true,
          cpUmsId: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
